config/routes.rb
Rails.application.routes.draw do
  devise_for :responsaveis
  resources :eventos
  root to: 'eventos#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(responsavel)
    # Define abilities for the passed in user here. For example:
    #
    #  responsavel ||= Responsavel.new # guest user (not logged in)
    cannot :manage, :all
    if responsavel
        can :manage, Evento, responsavel_id: responsavel.id
    else
        can [:index, :show], Evento
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	belongs_to :responsavel
end

app/models/responsavel.rb
class Responsavel < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :eventos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_responsavel!
  before_action :configure_permitted_parameters, if: :devise_controller?
  check_authorization unless: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
  	respond_to do |format|
  		format.html { render template: '../../public/404.html', status: 404 }
  		format.all { render nothing: true, status: 404 }
 	  end
	end

  def current_user
  	current_responsavel
  end

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nome
  end


end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :authenticate_responsavel!,except: [:index, :show]
  load_and_authorize_resource
  # GET /eventos
  # GET /eventos.json
  def index
    #@eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    #@evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    #@evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
   
    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nome, :descricao, :inicio, :fim, :fornecedor, :vagas, :local, :valor, :responsavel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :inicio %><br>
    <%= f.datetime_select :inicio %>
  </div>
  <div class="field">
    <%= f.label :fim %><br>
    <%= f.datetime_select :fim %>
  </div>
  <div class="field">
    <%= f.label :fornecedor %><br>
    <%= f.text_field :fornecedor %>
  </div>
  <div class="field">
    <%= f.label :responsavel_id %><br>
    <%= f.select :responsavel_id,Responsavel.all.map { |r|[r.email,r.id]  }%>
  </div>
  <div class="field">
    <%= f.label :vagas %><br>
    <%= f.number_field :vagas %>
  </div>
  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Inicio</th>
      <th>Fim</th>
      <th>Fornecedor</th>
      <th>Responsável</th>
      <th>Vagas</th>
      <th>Local</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.nome %></td>
        <td><%= evento.descricao %></td>
        <td><%= evento.inicio %></td>
        <td><%= evento.fim %></td>
        <td><%= evento.fornecedor %></td>
        <td><%= evento.responsavel.try :email %></td>
        <td><%= evento.vagas %></td>
        <td><%= evento.local %></td>
        <td><%= evento.valor %></td>
        <td><%= link_to 'Show', evento %></td>
        <% if responsavel_signed_in? %>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @evento.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @evento.descricao %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @evento.inicio %>
</p>

<p>
  <strong>Fim:</strong>
  <%= @evento.fim %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= @evento.fornecedor %>
</p>

<p>
  <strong>Vagas:</strong>
  <%= @evento.vagas %>
</p>

<p>
  <strong>Local:</strong>
  <%= @evento.local %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @evento.valor %>
</p>

<p>
  <strong>Responsável:</strong>
  <%= @evento.responsavel.try :email %>
</p>
<% if responsavel_signed_in? %>
<%= link_to 'Edit', edit_evento_path(@evento) %> |
<% end %>
<%= link_to 'Back', eventos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Randrios</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>	
<p>
	<%= current_responsavel.try :email %>
</p>
<%= link_to('Sair',destroy_responsavel_session_path, method: :delete) if responsavel_signed_in? %>
<%= link_to('Logar',new_responsavel_session_path) unless responsavel_signed_in? %>
<%= yield %>

</body>
</html>